# Generated by Django 5.0.2 on 2024-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('Pending', 'Pending'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=20),
        ),
    ]
