# Generated by Django 5.0.2 on 2024-02-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
