# Generated by Django 5.0.2 on 2024-02-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_doctoravailability_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
