# Generated by Django 5.0.2 on 2024-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_doctoravailability_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
