# Generated by Django 5.0.2 on 2024-02-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_doctoravailability_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientEmail',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientName',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientphoneNumber',
            field=models.IntegerField(default=False),
        ),
    ]
