# Generated by Django 5.0.2 on 2024-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_appointment_patientemail_appointment_patientname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
