# Generated by Django 5.0.2 on 2024-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_appointment_patientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientEmail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientphoneNumber',
            field=models.IntegerField(default=None),
        ),
    ]
