# Generated by Django 5.0.2 on 2024-02-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='day_of_week',
            new_name='day',
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=None, null=True),
        ),
    ]
