# Generated by Django 5.0.2 on 2024-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_day_of_week_appointment_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
