# Generated by Django 5.0.2 on 2024-02-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_doctoravailability_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
