# Generated by Django 5.0.2 on 2024-02-26 05:43

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
