# Generated by Django 5.0.2 on 2024-02-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_availability_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
