# Generated by Django 5.0.2 on 2024-02-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_availability_break_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='appointment_duration_mins',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
