# Generated by Django 5.0.2 on 2024-02-26 07:45

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_availability_appointment_duration_mins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(blank=True, default=False, null=True),
        ),
    ]
