# Generated by Django 5.0.2 on 2024-02-26 10:32

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_availability_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
    ]
