# Generated by Django 5.0.2 on 2024-02-26 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_availability_time_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.availability')),
            ],
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
