# Generated by Django 5.0.2 on 2024-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_daysofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysofweek',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
