# Generated by Django 5.0.2 on 2024-02-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_daysofweek_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='days_of_week',
            field=models.ManyToManyField(to='api.daysofweek'),
        ),
    ]
