# Generated by Django 5.0.2 on 2024-02-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_availability_days_of_week'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('user', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
    ]
