# Generated by Django 5.0.2 on 2024-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_datespecificavailability_timeslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
