# Generated by Django 5.0.2 on 2024-02-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='timeslot',
            field=models.ManyToManyField(blank=True, null=True, to='api.timeslot'),
        ),
    ]
