# Generated by Django 5.0.2 on 2024-02-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_doctoravailability_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='defualt_working_end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='defualt_working_start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
