# Generated by Django 5.0.2 on 2024-02-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_timeslot_end_time_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='defualt_working_end_time',
            new_name='default_working_end_time',
        ),
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='defualt_working_start_time',
            new_name='default_working_start_time',
        ),
    ]
