# Generated by Django 5.0.2 on 2024-03-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_patientrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='plan',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='diagnostic_test',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='family_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='follow_up_care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='further_testing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='impressions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='objective_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='objective_prognosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='patient_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='patient_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='physical_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='plan_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='plan_prognosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='review_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='social_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='vital_signs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='subjective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
