# Generated by Django 5.0.2 on 2024-03-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_patientrecord_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
