# Generated by Django 5.0.2 on 2024-03-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_customuser_registration_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider',
            field=models.CharField(default='email', max_length=15),
        ),
    ]
