# Generated by Django 5.0.2 on 2024-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_passwordresettoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='availability',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='user',
        ),
        migrations.DeleteModel(
            name='DateSpecificAvailability',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='DaysOfWeek',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
