# Generated by Django 5.0.2 on 2024-03-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
