# Generated by Django 5.0.2 on 2024-03-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='contactnumber',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contactnumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
