# Generated by Django 5.0.2 on 2024-03-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_remove_doctorprofile_contactnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='appointment_slot_duration',
            field=models.IntegerField(default=30),
        ),
    ]
