# Generated by Django 5.0.2 on 2024-03-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_doctoravailability_appointment_slot_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='appointment_slot_duration',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='appointment_slot_duration',
            field=models.IntegerField(default=30),
        ),
    ]
