# Generated by Django 5.0.3 on 2024-04-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_doctoravailability_appointment_slot_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('', 'None')], default='', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientDob',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='appointment_slot_duration',
            field=models.IntegerField(default=45),
        ),
    ]
