# Generated by Django 5.0.3 on 2024-04-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_appointment_gender_appointment_patientdob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='gender',
            new_name='patientGender',
        ),
    ]
