# Generated by Django 5.0.3 on 2024-04-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_rename_gender_appointment_patientgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('', 'None')], default='', max_length=8, null=True),
        ),
    ]
