# Generated by Django 5.0.3 on 2024-04-08 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location'),
        ),
    ]
