# Generated by Django 5.0.3 on 2024-04-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_doctorprofile_location_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='rescheduled_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rescheduled_day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rescheduled_end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rescheduled_start_time',
        ),
    ]
