# Generated by Django 5.0.3 on 2024-04-08 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_appointment_rescheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
