# Generated by Django 5.0.3 on 2024-04-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_patientrecord_created_at_patientrecord_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('None', 'None')], default='None', max_length=8, null=True),
        ),
    ]
