# Generated by Django 4.2.11 on 2024-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='default_working_end_time',
            field=models.TimeField(default='17:15'),
        ),
    ]
