# Generated by Django 4.2.11 on 2024-05-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_doctoravailability_default_working_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='default_working_end_time',
            field=models.TimeField(default='17:00'),
        ),
    ]
