# Generated by Django 4.2.11 on 2024-05-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_doctoravailability_default_working_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='specializations'),
        ),
    ]
