# Generated by Django 4.2.11 on 2024-06-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_appointment_confirmed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='break_end_time',
            field=models.TimeField(blank=True, default='13:30', null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='break_start_time',
            field=models.TimeField(blank=True, default='12:45', null=True),
        ),
    ]
