# Generated by Django 4.2.11 on 2024-07-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_doctoravailability_break_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='break_time_updated',
            field=models.BooleanField(default=False),
        ),
    ]
