# Generated by Django 4.2.11 on 2024-07-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_doctoravailability_break_time_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patientphoneNumber',
            new_name='contactnumber',
        ),
    ]
